### ISSUE TITLE
i_datenbank_konzept

### ISSUE THREAD

**Issue by Sippl** [schmitzdominic/ProjektSS17#107]
**Basiert auf:**

**Beschreibung:** Konzept für die Verwendung einer lokalen Datenbank ausarbeiten

**Zusatzinformationen:**

- Suche nach Programmbibliothek und Konzept über die Verwendung einer persistenten, relationalen, lokalen Datenbank, unter welcher die Daten lokal gespeichert werden.

**Kriterium:** Konzept wurde erstellt und Programmbibliothek wurde gefunden

**Comment by SemperF1** [comment]
Hier ein Tut um eine SQLLite DB in Android zu nutzen. 
http://www.programmierenlernenhq.de/android-sqlite-datenbank-tutorial/
