### ISSUE TITLE
i_drive_sync_recherche

### ISSUE THREAD

**Issue by Sippl** [schmitzdominic/ProjektSS17#113]
**Basiert auf:**

**Beschreibung:** Recherche nach einer geeigneten API für die drive_snyc Funktion.

**Zusatzinformationen:**

**Kriterium:** Geeignete API gefunden und vorgestellt.

**Comment by UliVe07** [comment]
https://developers.google.com/android/reference/com/google/android/gms/drive/FileUploadPreferences
