### ISSUE TITLE
i_fragment_implementieren

### ISSUE THREAD

**Issue by Sippl** [schmitzdominic/ProjektSS17#129]
**Basiert auf:** i_hauptseite_erstellen -  (A_Tab3Bons.java - box_tab3_bons_content.xml)

**Beschreibung:** Fragment für den Tab "Bons" implementieren. 

**Zusatzinformationen:**

- Bitte Namenskonvenktionen beachten

**Kriterium:** Fragment wurde für den Tab "Bons" implementiert

**Comment by Xantey** [comment]
Item macht in meinen Augen keinen Sinn, da der Tab Bons (wie auch Home & Statistik) bereits ein Fragment sind und man kein Fragment in ein Fragment lädt. Daher einfach nur das vorhandene Fragment verwenden und darauf die RecyclerView (in material design!) implementieren.

**Comment by schmitzdominic** [comment]
Stimmt hatte das nicht beachtet das letzte mal. Vielleicht sollten wir sogar die A_ Tabs dann in F_ Tabs refactoren und verschieben.

**Comment by Sippl** [comment]
@schmitzdominic Wäre glaub ich ne gute Sache, da ihr eh schon einen Ordern Fragmente erstellt habt. Allgemein sollten wir das Thema noch mal ansprechen, da ich gesehen habe, dass es jetzt Fragmente für Einstellungen etc gibt, dass wir festlegen wann ein Fragment erstellt werden sollte.
