### ISSUE TITLE
i_home_statistik_cardview

### ISSUE THREAD

**Issue by joeymez** [schmitzdominic/ProjektSS17#167]
Basiert auf:

Beschreibung: Hinzufügen einer CardView mit drei bis sechs Elementen, in welchem Statistiken angezeigt werden.

Zusatzinformationen: Bitte Namenskonvention beachten!

Kriterium: i_home_liste_implementieren ist die Basis dazu

**Comment by Sippl** [comment]
Wird nach Wunsch des Teams, mit i_home_statistik_cardview zusammengefügt. Sozusagen wird nur ein Branch und ein Pull Request gestellt. @UliVe07 @ImSeDanny @dontcallme @SshaBrn
