### ISSUE TITLE
i_tutorial_suchen

### ISSUE THREAD

**Issue by schmitzdominic** [schmitzdominic/ProjektSS17#18]
Jeder sucht ein Tutorial um sich die Grundkenntnisse für Android Studio / Struktur / App-Entwicklung bei zu bringen. (Vorschläge sammeln)

**Comment by UliVe07** [comment]
- Ganz einfaches Tutorial er erklärt von Grund auf aber geht nicht zu sehr ins Detail (Video)
   https://www.youtube.com/watch?v=s2hJbfJ0gQU&list=FLIfILsZUvG5Ym_WquUAVgJw&index=1
- Tutorial Grundlagen geht bisschen mehr ins Detail (Text)
   http://www.programmierenlernenhq.de/tutorial-android-studio-projekt-erstellen/

**Comment by Xantey** [comment]
https://www.youtube.com/user/eddydn71

zb: Weather App

**Comment by SemperF1** [comment]
- Allgemeine Tipps zur einfachen Handhabung mit Android Studio 
https://medium.com/@mmbialas/50-android-studio-tips-tricks-resources-you-should-be-familiar-with-as-an-android-developer-af86e7cf56d2#.5c6kjzy7s

**Comment by schmitzdominic** [comment]
Ein ehemaliger Arbeitskollege (Werkstudent) von Pro7 hatte eine Vorlesung über Android Studio und App Entwicklung mit Material Design. Er war so nett mir seine Vorlesungsunterlagen zu geben. Hab die mal in unser Drive gelegt ;)

https://drive.google.com/drive/folders/0B2GJsqm87zxCS0dtRDRJWkdicFE

**Comment by Sippl** [comment]
Android Studio im Überblick auf deutsch. In dem Video wird toll erklärt wie Android Studio aufgebaut ist (Bereiche / Toolbars / Gradle etc.), es wird jedoch nicht zu sehr ins Detail gegangen).  https://www.youtube.com/watch?v=3Eo6F41MGJQ&feature=youtu.be

**Comment by joeymez** [comment]
Crashkurs Java: -> fettgedrucktes könnte wichtig werden, der Rest ist meiner Meinung unwichtig
----------------------------------------------------------------------------------------------------------

Einführung (1/21) - https://www.youtube.com/watch?v=Ztc6_elMg60
IDE´s (2/21) - https://www.youtube.com/watch?v=CX95c3Dw2Ws&t=1s
Projekte erstellen + Variablen (3a/21) - https://www.youtube.com/watch?v=m_1shoOdzNk
Weiter Variablen + Ausgaben (3b/21) - https://www.youtube.com/watch?v=0HfmYxFeYcA
Rechnen + Strings (4/21) - https://www.youtube.com/watch?v=hJgn-YPUZRY
Arrays (5/21) - https://www.youtube.com/watch?v=jWD2XiyJcHs&t=40s
IF-Bedingungen (6/21) - https://www.youtube.com/watch?v=i-6TfYTnekI
SWITCH-Bedingung (7/21) - https://www.youtube.com/watch?v=1fveBSNKoTo
Bedingungen verknüpfen (8/21) - https://www.youtube.com/watch?v=6IjgvKDAa3Q
**Kommentare im Programm (9/21)** - https://www.youtube.com/watch?v=D8XsHZ5VXGE
**Schleifen I WHILE,DO-WHILE (10/21)** - https://www.youtube.com/watch?v=JxdVL5AmCP8
**Schleifen II FOR (11/21)** - https://www.youtube.com/watch?v=w07PEn0R64g
Funktionen (12/21) - https://www.youtube.com/watch?v=t3rNdJxGGm0
Rekursion (13/21) - https://www.youtube.com/watch?v=OeMXh7rPqp4
**Klassen (14/21)** - https://www.youtube.com/watch?v=DO0_r3sr9ak
**Vererbungen (15/21)** - https://www.youtube.com/watch?v=CErVXcyTIZ8
Arraylist Generische Klasse (16/21) - https://www.youtube.com/watch?v=l_XrkiZFE08
**Modifier PUBLIC, PRIVATE, ETC. (17/21)** - https://www.youtube.com/watch?v=toXVbadvlbY
**Tastatur & Dateien einlesen (18/21)** - https://www.youtube.com/watch?v=xoRZ75uyzvg
In Datein Schreiben (19/21) - https://www.youtube.com/watch?v=pPEShwmJAMc
Fehlerbehandlung (20/21) - https://www.youtube.com/watch?v=MUzCKDp-PIU
Sonstige Infos (21/21) - https://www.youtube.com/watch?v=Q1Zs4QnkUFs

**Comment by ImSeDanny** [comment]
Android Studio Tutorial für Anfänger
http://www.androidauthority.com/android-studio-tutorial-beginners-637572/

App mit Androdi Studio entwickeln
http://mobilesiri.com/develop-your-first-android-app-using-android-stuido-tutorial/

Youtube Video How to build an Android App
https://www.youtube.com/watch?v=F-k5gwz_91o

Java Tutorial (Grundlagen etc)
https://javabeginners.de/index.php
