### ISSUE TITLE
i_notifications_konzept

### ISSUE THREAD

**Issue by joeymez** [schmitzdominic/ProjektSS17#218]
**Basiert auf:**
i_general_notifications (e_notifications)

**Beschreibung:** 
Informieren wie man Notifications (Benachrichtigungen) einbinden kann und was man benachrichtigt kriegt
Erste Implementierung (wenn möglich)

**Zusatzinformationen:**
Bitte Namenskonvenktion beachten

**Kriterium:** 
Fertige Idee wie man Notifications implentiert, sowie was man benachrichtigt kriegt
Erste Implementierung der Idee

**Comment by Sippl** [comment]
Überlegungen wo Notifications nice to have wären:
- Monatsbilanz (Ende des Monats: Sie haben .... Geld in diesem Monat ausgegeben). 
- oder Wochenbilanz (Endes jeder Woche: Sie haben ... Geld in dieser Woche ausgegeben).
- Budget (Meldung bei 15 % RestBudget)..
- Garantie (Garantie ihres eingegebenen Bons endet in 2 Wochen). 
- Backup (Backup abgeschlossen, oder bei Neuinstallation "Verknüfen sie ihre app mit Google Drive um ein Backup zu erstellen etc.)
- Meilensteine (500 eingescannte bons , 1000 eingescannte bons....)

**Comment by Sippl** [comment]
Funktion in Klasse S implementiert. Diese kann von beliebigen Orten mit Parametern aufgerufen werden.
