### ISSUE TITLE
i_ideen_sammeln

### ISSUE THREAD

**Issue by schmitzdominic** [schmitzdominic/ProjektSS17#29]
Ideen für unsere App sammeln

**Comment by schmitzdominic** [comment]
Widgets z.B. das direkt die Kamera gestartet wird

**Comment by SemperF1** [comment]
- Vergleich zwischen verschiedenen Supermärkten. Abgleich der Preise.
- Bilanz erstellen wie viel für welchen Artikel ausgegeben wird (Ich zahle in der Regel ...€ im Monat für Jogurt)

**Comment by Sippl** [comment]
- Einscannen der Belege => Voranzeige ob alles richtig erkannt wurde => Manuelles Korrigieren ermöglichen => Wenn alles passt werden die Daten gespeichert
- Auswertungen bei welchen Supermärkten / Geschäften ich wie oft einkaufe
- Auswertung wie viel ich monatlich für bestimmte Artikel ausgebe
- Möglichkeit ein festes Budget einzugeben und stets anzuzeigen wie viel man im Monat noch ausgeben darf
- Übermittlungsfunktionen (z.B. Daten auf PC verschicken)

**Comment by joeymez** [comment]
- Digitalisierung der Quittungen (& Abspeichern in eine Cloud >> z.B. GDrive, Dropbox, etc.)
- Zu Fabis Budgetierungs-Idee: Vorschläge machen welche Produkte zum vorhanden Budget noch gekauft werden können 
- Merken der meist gekauften Artikel und Berücksichtigung dieser in der Budgetierungs-Idee
- Eine Art Dashboard (Auswertungen / Grafiken / etc.) auf der Startseite bezüglich aller Einkäufe zur schnellen Übersicht
- Sharing-Funktion der Produktinformation, um beispielsweise anderen Anwendern den günstigsten Preis zu zeigen
-Filterfunktionen in der Auswertung >> z.B. welche Produkte waren am günstigen / in welchen Supermarkt wurden diese eingekauft ...
- Speicherung alle Produktinformationen in einer Datenbank (z.B. Marke, Gewicht, Preis, Inhaltsstoffe, evtl. Bild des Produkts, etc.)

-> PS: weitere Ideen folgen im Laufe der Entwicklung! ;)
