### ISSUE TITLE
i_db_recherche_anfrage

### ISSUE THREAD

**Issue by schmitzdominic** [schmitzdominic/ProjektSS17#68]
**Basiert auf:**

Beschreibung: Nach einer Datenbank zum Matchen der Strings suchen und bei dem Besitzer nach Freigabe Anfragen.

**Zusatzinformationen:**
http://www.discounter-preisvergleich.de/
- Nach geeingeter Datenbank recherieren (Tipp: Auf Marcus zu gehen, er hat bzgl. dessen bereits geschaut)
- Bei Besitzer der Datenbank anfragen, ob wir diese für unsere App nutzen dürfen (Evtl. mit Hinweis darauf, dass es ein Studien Projekt ist und keine kommerzielle Anwendung)

**Kriterium:** Wir wissen welche DB wir benutzen und haben schriftliches OK von DB-Owner

**Comment by joeymez** [comment]
Mail an den Anbieter der Website Discounter Vergleich wurde verfasst. Anfrage auf einen Zugriff / Kopie seiner Produktdatenbank wurde gestellt...

>> Sobald ich eine Rückmeldung erhalte (unabhängig ob negativ / positiv), werde ich dieses Issue closen! :)

**Comment by Sippl** [comment]
@joeymez Wurde beschlossen nur diesen einen Anbieter anzufragen?
