### ISSUE TITLE
i_projekttag_konzept

### ISSUE THREAD

**Issue by schmitzdominic** [schmitzdominic/ProjektSS17#76]
**Basiert auf:**

**Beschreibung:** 
- Stand planen
- Plakate planen
- T-Shirts designen + Vorstellen + Bestellen!

**Zusatzinformationen:**

**Kriterium:**
Siehe Oben.

**Comment by Sippl** [comment]
Infos: und Checkliste unter: https://drive.google.com/drive/folders/0B9qV3EwhEWCuUXRiTllzc1VMdFE
