### ISSUE TITLE
i_board_doku_erstellen

### ISSUE THREAD

**Issue by schmitzdominic** [schmitzdominic/ProjektSS17#80]
**Basiert auf:**

**Beschreibung:** Dokumentation über unser Board (Spalten beschreiben) + Zusätzliche grundlegende Informationen zu den Scrum Begriffen

**Zusatzinformationen:** Zusätzlich sollten wir das vom Scrum Master mitgeschriebenene Feedback aus der Retrospective immer veröffentlichen, damit eine kontinuierliche Verbesserung des Scrum Prozesses gewährleistet ist. 

**Kriterium:** Ein Google Doc wurde erstellt das allen mit dem Board Umgang weiterhilft.

**Comment by Sippl** [comment]
Hab die Beschreibung mal geupdatet.
