### ISSUE TITLE
i_activity_gruppen

### ISSUE THREAD

**Issue by schmitzdominic** [schmitzdominic/ProjektSS17#90]
**Basiert auf:** i_hauptseite_erstellen

**Beschreibung:** Die Activity Gruppen muss erstellt werden und mit der Hauptseite verknüpft werden.

**Zusatzinformationen:**   
Bitte Namenskonvenktion beachten: A_Gruppen
- Basic Activity  
- WICHTIG! Hierarchical Parent -> Bitte von der Vorherigen Seite (i_hauptseite_erstellen)  

**Kriterium:** Activity A_Gruppen wurde erstellt und verknüpft.

**Comment by Sippl** [comment]
Ist doch doppelt? Kann raus oder? @schmitzdominic
