### ISSUE TITLE
i_statistik_konzept

### ISSUE THREAD

**Issue by schmitzdominic** [schmitzdominic/ProjektSS17#97]
**Basiert auf:**

**Beschreibung:** Konzept für die Statistiken ausarbeiten

**Zusatzinformationen:**

**Kriterium:** Konzept wurde erstellt.

**Comment by Xantey** [comment]
Doc für Charts von Google selbst.

https://developers.google.com/chart/interactive/docs/gallery/barchart

**Comment by Xantey** [comment]
Git für Charts von William.

https://github.com/diogobernardino/WilliamChart

**Comment by Xantey** [comment]
MPAndroidChart

https://github.com/PhilJay/MPAndroidChart

**Comment by Xantey** [comment]
Die Statistik Seite wird gefüllt mit Statistiken aus diesen Libraries und ist (hoffentlich bzw. wäre nice) durch Fragmente unterschiedlich darstellbar. (Kacheln oder art Liste und jeweils verschieden anordbar)

**Comment by Xantey** [comment]
Kleine Übersicht aus StackOverflow für alle die auch mal vergleichen wollen.

http://stackoverflow.com/questions/26467376/android-charting-libraries

**Comment by schmitzdominic** [comment]
Top leute 👍
